// Refresh the self-hosted Noto Sans Georgian files in src/fonts and the
// @font-face block at the top of src/app.css.
//
//   node tools/fetch-fonts.mjs
//
// This is the only thing in the repo that talks to Google. It runs by hand when
// the upstream face is revised; the app itself never reaches the network. Google
// serves one variable woff2 per subset and hands back identical bytes for every
// weight, so each subset is stored once and the four weights the UI uses come
// off the 400-700 axis of that single file.
import { writeFileSync, readFileSync, mkdirSync } from 'node:fs'
import { fileURLToPath } from 'node:url'
import { dirname, join } from 'node:path'

const ROOT = join(dirname(fileURLToPath(import.meta.url)), '..')
const FAMILY = 'Noto+Sans+Georgian:wght@400;500;600;700'
// Georgian carries Mkhedruli; latin covers the English locale and the numerals.
const SUBSETS = ['latin', 'latin-ext', 'georgian']
// woff2 is only offered to a browser-shaped user agent.
const UA = 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36'
const MARK = '/* --- generated by tools/fetch-fonts.mjs; edit below this line --- */'

const get = async (url, as) => {
  const r = await fetch(url, { headers: { 'user-agent': UA } })
  if (!r.ok) throw new Error(`${r.status} ${r.statusText} — ${url}`)
  return as === 'buffer' ? Buffer.from(await r.arrayBuffer()) : r.text()
}

const css = await get(`https://fonts.googleapis.com/css2?family=${FAMILY}&display=swap`)

// One @font-face block per subset per weight, each labelled with a leading
// comment naming the subset. Keep the first of each; the weights are the same file.
const found = new Map()
for (const block of css.split('/*').slice(1)) {
  const subset = block.slice(0, block.indexOf('*/')).trim()
  if (!SUBSETS.includes(subset) || found.has(subset)) continue
  found.set(subset, {
    url: /url\((https:[^)]+)\)/.exec(block)?.[1],
    range: /unicode-range:\s*([^;]+);/.exec(block)?.[1].trim(),
  })
}
for (const s of SUBSETS) {
  if (!found.get(s)?.url || !found.get(s)?.range) throw new Error(`no usable @font-face for subset "${s}"`)
}

mkdirSync(join(ROOT, 'src/fonts'), { recursive: true })
const faces = []
for (const subset of SUBSETS) {
  const { url, range } = found.get(subset)
  const file = `noto-sans-georgian-${subset}.woff2`
  const bytes = await get(url, 'buffer')
  writeFileSync(join(ROOT, 'src/fonts', file), bytes)
  console.log(`  ${file}  ${(bytes.length / 1024).toFixed(1)} kB`)
  faces.push(`/* ${subset} */
@font-face {
  font-family: "Noto Sans Georgian";
  font-style: normal;
  font-weight: 400 700;
  font-stretch: 100%;
  font-display: swap;
  src: url("./fonts/${file}") format("woff2");
  unicode-range: ${range};
}`)
}

// Replace everything above the marker, so hand-written rules below survive.
const appCss = join(ROOT, 'src/app.css')
const rest = readFileSync(appCss, 'utf8').split(MARK).pop().replace(/^\n+/, '')
const header = `/* Noto Sans Georgian, self-hosted so the app renders Mkhedruli with no network.
   One variable woff2 per subset: Google serves the same bytes for every weight,
   so the four weights the UI uses come from the 400-700 axis of a single file.
   Regenerate with: npm run fonts */
${faces.join('\n')}
${MARK}

`
writeFileSync(appCss, header + rest)
console.log(`  src/app.css  @font-face block rewritten (${SUBSETS.length} subsets)`)
